services:
  mongodb:
    image: mongo:7.0
    container_name: rest-api-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rest-api
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: